theme: jekyll-theme-minimal
title: [Dilmi Perera]
description: [A github portfolio to showcase my Data Science projects.]
logo: [https://avatars0.githubusercontent.com/u/1021436?s=460&u=5929e70c11338fdd02412614c7e8bc46608f97d0&v=4]
