theme: jekyll-theme-minimal
title: [Dilmi Perera]
description: [A github portfolio to showcase my Data Science projects.\n About me: I am a Biinformatics Scientist with 5+ years of experience working on data science projects in cancer genomics. My training is in Computer Science(BSc) and Bioinformatics (PhD). I enjoy working on challenging machine learning problems in different fields and I created this portfolio to showcase my work. ]

